spring.application.name=ToyStore

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.web.resources.static-locations=classpath:/static/,file:${user.home}/Downloads/

server.forward-headers-strategy=framework

server.error.include-stacktrace=never
server.error.include-message=never
server.servlet.session.cookie.same-site=lax

spring.config.import=optional:application-secret.properties









